version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errorlint
    - gocritic
    - makezero
    - misspell
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
  settings:
    errcheck:
      exclude-functions:
        - (net/http.ResponseWriter).Write
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - appendAssign
        - deferInLoop
        - hugeParam
        - rangeValCopy
  exclusions:
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - bodyclose
          - errcheck
          - prealloc
          - unparam
          - usestdlibvars

formatters:
  enable:
    - gofmt
