// Code generated by bowline. DO NOT EDIT.

package ledgerclient

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"iter"
	"mime/multipart"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/bowlinedev/bowline"
)

// InvoiceLocked is returned when an invoice can no longer change.
type InvoiceLocked struct {
	ID     int64  `json:"id"`
	Status Status `json:"status"`
}

type AttachInput struct {
	InvoiceId int64 `json:"invoiceId"`
}

type Attachment struct {
	ID          int64     `json:"id"`
	InvoiceId   int64     `json:"invoiceId"`
	Name        string    `json:"name"`
	ContentType string    `json:"contentType"`
	Size        int64     `json:"size"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type CreateInvoiceInput struct {
	CustomerId int64   `json:"customerId"`
	Lines      []Line  `json:"lines"`
	Note       *string `json:"note,omitempty"`
}

type Customer struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type GetCustomerInput struct {
	ID int64 `json:"id"`
}

type GetInvoiceInput struct {
	ID int64 `json:"id"`
}

type HealthOutput struct {
	Ok      bool   `json:"ok"`
	Version string `json:"version"`
}

type Invoice struct {
	ID         int64     `json:"id"`
	CustomerId int64     `json:"customerId"`
	Status     Status    `json:"status"`
	Total      string    `json:"total"`
	Lines      []Line    `json:"lines"`
	Note       *string   `json:"note,omitempty"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type Line struct {
	Description string `json:"description"`
	Quantity    int32  `json:"quantity"`
	UnitPrice   string `json:"unitPrice"`
}

type ListAttachmentsInput struct {
	InvoiceId int64 `json:"invoiceId"`
}

type ListInvoicesInput struct {
	Cursor *string `json:"cursor,omitempty"`
	Limit  int32   `json:"limit"`
	Status *Status `json:"status,omitempty"`
}

type Page[T any] struct {
	Items      []T     `json:"items"`
	NextCursor *string `json:"nextCursor,omitempty"`
}

type SearchCustomersInput struct {
	Query string `json:"query"`
}

type Status string

const (
	StatusDraft Status = "draft"
	StatusSent  Status = "sent"
	StatusPaid  Status = "paid"
	StatusVoid  Status = "void"
)

type VoidInvoiceInput struct {
	ID int64 `json:"id"`
}

type WatchInput struct {
	Status *Status `json:"status,omitempty"`
}

// Client calls the API described by the contract.
type Client struct {
	Customers CustomersClient
	Invoices  InvoicesClient

	base    string
	http    *http.Client
	headers func(context.Context) (http.Header, error)
}

// Option configures a Client.
type Option func(*Client)

// WithHTTPClient replaces the http.Client used for every call.
func WithHTTPClient(c *http.Client) Option {
	return func(cl *Client) { cl.http = c }
}

// WithHeaders adds headers to every request, for example an Authorization header derived from ctx.
func WithHeaders(fn func(context.Context) (http.Header, error)) Option {
	return func(cl *Client) { cl.headers = fn }
}

// New returns a client for the API served at baseURL.
func New(baseURL string, opts ...Option) *Client {
	c := &Client{base: strings.TrimRight(baseURL, "/"), http: http.DefaultClient}
	for _, opt := range opts {
		opt(c)
	}
	c.Customers = CustomersClient{c: c}
	c.Invoices = InvoicesClient{c: c}
	return c
}

// Health calls health.
func (c *Client) Health(ctx context.Context) (HealthOutput, error) {
	var out HealthOutput
	err := c.call(ctx, "health", http.MethodGet, struct{}{}, &out)
	return out, err
}

// CustomersClient groups the procedures under "customers".
type CustomersClient struct {
	c *Client
}

// Get calls customers.get.
func (c CustomersClient) Get(ctx context.Context, in GetCustomerInput) (Customer, error) {
	var out Customer
	err := c.c.call(ctx, "customers.get", http.MethodGet, in, &out)
	return out, err
}

// Search finds customers whose name or email contains the query.
func (c CustomersClient) Search(ctx context.Context, in SearchCustomersInput) (Page[Customer], error) {
	var out Page[Customer]
	err := c.c.call(ctx, "customers.search", http.MethodPost, in, &out)
	return out, err
}

// InvoicesClient groups the procedures under "invoices".
type InvoicesClient struct {
	c *Client
}

// Attach stores a file against an invoice.
func (c InvoicesClient) Attach(ctx context.Context, in AttachInput, name string, file io.Reader) (Attachment, error) {
	var out Attachment
	err := c.c.upload(ctx, "invoices.attach", in, name, file, &out)
	return out, err
}

// Attachments calls invoices.attachments.
func (c InvoicesClient) Attachments(ctx context.Context, in ListAttachmentsInput) (Page[Attachment], error) {
	var out Page[Attachment]
	err := c.c.call(ctx, "invoices.attachments", http.MethodGet, in, &out)
	return out, err
}

// Create calls invoices.create.
func (c InvoicesClient) Create(ctx context.Context, in CreateInvoiceInput) (Invoice, error) {
	var out Invoice
	err := c.c.call(ctx, "invoices.create", http.MethodPost, in, &out)
	return out, err
}

// Get returns one invoice by ID.
func (c InvoicesClient) Get(ctx context.Context, in GetInvoiceInput) (Invoice, error) {
	var out Invoice
	err := c.c.call(ctx, "invoices.get", http.MethodGet, in, &out)
	return out, err
}

// List returns a page of invoices, optionally filtered by status.
func (c InvoicesClient) List(ctx context.Context, in ListInvoicesInput) (Page[Invoice], error) {
	var out Page[Invoice]
	err := c.c.call(ctx, "invoices.list", http.MethodGet, in, &out)
	return out, err
}

// Void cancels a draft or sent invoice.
func (c InvoicesClient) Void(ctx context.Context, in VoidInvoiceInput) (Invoice, error) {
	var out Invoice
	err := c.c.call(ctx, "invoices.void", http.MethodPost, in, &out)
	return out, err
}

// Watch streams every invoice change.
func (c InvoicesClient) Watch(ctx context.Context, in WatchInput) (iter.Seq2[Invoice, error], error) {
	resp, err := c.c.open(ctx, "invoices.watch", http.MethodGet, in)
	if err != nil {
		return nil, err
	}
	return stream[Invoice](resp, "invoices.watch"), nil
}

// ErrorDetails carries a declared error variant's name and its details payload.
type ErrorDetails struct {
	Type string
	Raw  json.RawMessage
}

// VariantOf returns the declared error variant name carried by err, or "".
func VariantOf(err error) string {
	var be *bowline.Error
	if !errors.As(err, &be) {
		return ""
	}
	if d, ok := be.Details.(ErrorDetails); ok {
		return d.Type
	}
	return ""
}

// DetailsAs decodes the details payload of err into T when err is a Bowline error with details.
func DetailsAs[T any](err error) (T, bool) {
	var out T
	var be *bowline.Error
	if !errors.As(err, &be) {
		return out, false
	}
	d, ok := be.Details.(ErrorDetails)
	if !ok || len(d.Raw) == 0 {
		return out, false
	}
	if json.Unmarshal(d.Raw, &out) != nil {
		return out, false
	}
	return out, true
}

func (c *Client) request(ctx context.Context, path, method string, in any, accept string) (*http.Request, error) {
	body, err := json.Marshal(in)
	if err != nil {
		return nil, &bowline.Error{Code: bowline.Internal, Message: fmt.Sprintf("encoding input for %s: %v", path, err)}
	}
	target := c.base + "/" + path
	var req *http.Request
	if method == http.MethodGet {
		target += "?input=" + url.QueryEscape(string(body))
		req, err = http.NewRequestWithContext(ctx, method, target, nil)
	} else {
		req, err = http.NewRequestWithContext(ctx, method, target, bytes.NewReader(body))
	}
	if err != nil {
		return nil, &bowline.Error{Code: bowline.Internal, Message: err.Error()}
	}
	if err := c.applyHeaders(ctx, req); err != nil {
		return nil, err
	}
	req.Header.Set("Accept", accept)
	if method != http.MethodGet {
		req.Header.Set("Content-Type", "application/json")
	}
	return req, nil
}

func (c *Client) applyHeaders(ctx context.Context, req *http.Request) error {
	if c.headers == nil {
		return nil
	}
	h, err := c.headers(ctx)
	if err != nil {
		return err
	}
	for k, vs := range h {
		req.Header[k] = vs
	}
	return nil
}

func (c *Client) do(ctx context.Context, req *http.Request, path string) (*http.Response, error) {
	resp, err := c.http.Do(req)
	if err != nil {
		if ctx.Err() != nil {
			return nil, &bowline.Error{Code: bowline.Canceled, Message: "request canceled"}
		}
		return nil, &bowline.Error{Code: bowline.Unavailable, Message: fmt.Sprintf("calling %s: %v", path, err)}
	}
	if resp.StatusCode >= 400 {
		defer resp.Body.Close()
		data, err := io.ReadAll(resp.Body)
		if err != nil {
			return nil, &bowline.Error{Code: bowline.Unavailable, Message: fmt.Sprintf("reading %s: %v", path, err)}
		}
		return nil, decodeError(resp.StatusCode, data, path)
	}
	return resp, nil
}

func (c *Client) call(ctx context.Context, path, method string, in, out any) error {
	req, err := c.request(ctx, path, method, in, "application/json")
	if err != nil {
		return err
	}
	resp, err := c.do(ctx, req, path)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	return decodeBody(resp.Body, path, out)
}

func decodeBody(body io.Reader, path string, out any) error {
	data, err := io.ReadAll(body)
	if err != nil {
		return &bowline.Error{Code: bowline.Unavailable, Message: fmt.Sprintf("reading %s: %v", path, err)}
	}
	if out == nil || len(bytes.TrimSpace(data)) == 0 {
		return nil
	}
	if err := json.Unmarshal(data, out); err != nil {
		return &bowline.Error{Code: bowline.Internal, Message: fmt.Sprintf("decoding %s: %v", path, err)}
	}
	return nil
}

func decodeError(status int, data []byte, path string) error {
	var env struct {
		Error struct {
			Code    bowline.Code    `json:"code"`
			Message string          `json:"message"`
			Type    string          `json:"type"`
			Details json.RawMessage `json:"details"`
			Issues  []bowline.Issue `json:"issues"`
		} `json:"error"`
	}
	if err := json.Unmarshal(data, &env); err != nil || env.Error.Code == "" {
		return &bowline.Error{Code: bowline.Unknown, Message: fmt.Sprintf("HTTP %d from %s", status, path)}
	}
	e := &bowline.Error{Code: env.Error.Code, Message: env.Error.Message, Issues: env.Error.Issues}
	if env.Error.Type != "" || len(env.Error.Details) > 0 {
		e.Details = ErrorDetails{Type: env.Error.Type, Raw: env.Error.Details}
	}
	return e
}

func (c *Client) open(ctx context.Context, path, method string, in any) (*http.Response, error) {
	req, err := c.request(ctx, path, method, in, "text/event-stream")
	if err != nil {
		return nil, err
	}
	return c.do(ctx, req, path)
}

func stream[Out any](resp *http.Response, path string) iter.Seq2[Out, error] {
	return func(yield func(Out, error) bool) {
		defer resp.Body.Close()
		scanner := bufio.NewScanner(resp.Body)
		scanner.Buffer(make([]byte, 0, 64<<10), 16<<20)
		event, data := "", ""
		flush := func() bool {
			defer func() { event, data = "", "" }()
			switch event {
			case "message":
				var out Out
				if err := json.Unmarshal([]byte(data), &out); err != nil {
					var zero Out
					return yield(zero, &bowline.Error{Code: bowline.Internal, Message: fmt.Sprintf("decoding %s: %v", path, err)})
				}
				return yield(out, nil)
			case "error":
				var zero Out
				yield(zero, decodeError(http.StatusInternalServerError, []byte(data), path))
				return false
			case "done":
				return false
			}
			return true
		}
		for scanner.Scan() {
			line := scanner.Text()
			switch {
			case line == "":
				if event != "" && !flush() {
					return
				}
			case strings.HasPrefix(line, "event: "):
				event = strings.TrimPrefix(line, "event: ")
			case strings.HasPrefix(line, "data: "):
				data = strings.TrimPrefix(line, "data: ")
			}
		}
		if err := scanner.Err(); err != nil {
			var zero Out
			yield(zero, &bowline.Error{Code: bowline.Unavailable, Message: fmt.Sprintf("reading %s: %v", path, err)})
		}
	}
}

func (c *Client) upload(ctx context.Context, path string, in any, name string, file io.Reader, out any) error {
	input, err := json.Marshal(in)
	if err != nil {
		return &bowline.Error{Code: bowline.Internal, Message: fmt.Sprintf("encoding input for %s: %v", path, err)}
	}
	pr, pw := io.Pipe()
	writer := multipart.NewWriter(pw)
	go func() {
		part, err := writer.CreatePart(map[string][]string{"Content-Disposition": {`form-data; name="input"`}, "Content-Type": {"application/json"}})
		if err == nil {
			_, err = part.Write(input)
		}
		if err == nil {
			var fw io.Writer
			fw, err = writer.CreateFormFile("file", name)
			if err == nil {
				_, err = io.Copy(fw, file)
			}
		}
		if err == nil {
			err = writer.Close()
		}
		pw.CloseWithError(err)
	}()
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.base+"/"+path, pr)
	if err != nil {
		return &bowline.Error{Code: bowline.Internal, Message: err.Error()}
	}
	if err := c.applyHeaders(ctx, req); err != nil {
		return err
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("Content-Type", writer.FormDataContentType())
	resp, err := c.do(ctx, req, path)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	return decodeBody(resp.Body, path, out)
}
