// Generated by bowline. DO NOT EDIT.

import 'package:bowline/bowline.dart';

class AttachInput {
  AttachInput({required this.invoiceId});

  factory AttachInput.fromJson(Map<String, Object?> json) => AttachInput(
        invoiceId: readInt(json, 'invoiceId'),
      );

  final int invoiceId;

  Map<String, Object?> toJson() => {
        'invoiceId': invoiceId,
      };

  List<Issue> validate() => [
        if (invoiceId == 0) Issue(['invoiceId'], 'required', 'is required'),
      ];
}

class Attachment {
  Attachment({required this.id, required this.invoiceId, required this.name, required this.contentType, required this.size, required this.createdAt, required this.updatedAt});

  factory Attachment.fromJson(Map<String, Object?> json) => Attachment(
        id: readInt(json, 'id'),
        invoiceId: readInt(json, 'invoiceId'),
        name: readString(json, 'name'),
        contentType: readString(json, 'contentType'),
        size: readInt(json, 'size'),
        createdAt: readTimestamp(json, 'createdAt'),
        updatedAt: readTimestamp(json, 'updatedAt'),
      );

  final int id;

  final int invoiceId;

  final String name;

  final String contentType;

  final int size;

  final DateTime createdAt;

  final DateTime updatedAt;

  Map<String, Object?> toJson() => {
        'id': id,
        'invoiceId': invoiceId,
        'name': name,
        'contentType': contentType,
        'size': size,
        'createdAt': encodeTimestamp(createdAt),
        'updatedAt': encodeTimestamp(updatedAt),
      };

  List<Issue> validate() => const [];
}

class CreateInvoiceInput {
  CreateInvoiceInput({required this.customerId, required this.lines, this.note});

  factory CreateInvoiceInput.fromJson(Map<String, Object?> json) => CreateInvoiceInput(
        customerId: readInt(json, 'customerId'),
        lines: readList(json, 'lines', (v0) => Line.fromJson(asObject(v0))),
        note: readOptionalString(json, 'note'),
      );

  final int customerId;

  final List<Line> lines;

  final String? note;

  Map<String, Object?> toJson() => {
        'customerId': customerId,
        'lines': [for (final e0 in lines) e0.toJson()],
        if (note != null) 'note': note,
      };

  List<Issue> validate() {
    final note = this.note;
    return [
      if (customerId == 0) Issue(['customerId'], 'required', 'is required'),
      if (lines.isEmpty) Issue(['lines'], 'required', 'is required'),
      for (final (i0, e0) in lines.indexed) ...[...prefixed(['lines', '$i0'], e0.validate())],
      if (note != null) if (note.runes.length > 500) Issue(['note'], 'max', 'must be at most 500 characters'),
    ];
  }
}

class Customer {
  Customer({required this.id, required this.name, required this.email, required this.createdAt, required this.updatedAt});

  factory Customer.fromJson(Map<String, Object?> json) => Customer(
        id: readInt(json, 'id'),
        name: readString(json, 'name'),
        email: readString(json, 'email'),
        createdAt: readTimestamp(json, 'createdAt'),
        updatedAt: readTimestamp(json, 'updatedAt'),
      );

  final int id;

  final String name;

  final String email;

  final DateTime createdAt;

  final DateTime updatedAt;

  Map<String, Object?> toJson() => {
        'id': id,
        'name': name,
        'email': email,
        'createdAt': encodeTimestamp(createdAt),
        'updatedAt': encodeTimestamp(updatedAt),
      };

  List<Issue> validate() => [
        if (name.isEmpty) Issue(['name'], 'required', 'is required'),
        if (email.isEmpty) Issue(['email'], 'required', 'is required'),
        if (!isEmail(email)) Issue(['email'], 'email', 'must be a valid email address'),
      ];
}

class GetCustomerInput {
  GetCustomerInput({required this.id});

  factory GetCustomerInput.fromJson(Map<String, Object?> json) => GetCustomerInput(
        id: readInt(json, 'id'),
      );

  final int id;

  Map<String, Object?> toJson() => {
        'id': id,
      };

  List<Issue> validate() => [
        if (id == 0) Issue(['id'], 'required', 'is required'),
      ];
}

class GetInvoiceInput {
  GetInvoiceInput({required this.id});

  factory GetInvoiceInput.fromJson(Map<String, Object?> json) => GetInvoiceInput(
        id: readInt(json, 'id'),
      );

  final int id;

  Map<String, Object?> toJson() => {
        'id': id,
      };

  List<Issue> validate() => [
        if (id == 0) Issue(['id'], 'required', 'is required'),
      ];
}

class HealthOutput {
  HealthOutput({required this.ok, required this.version});

  factory HealthOutput.fromJson(Map<String, Object?> json) => HealthOutput(
        ok: readBool(json, 'ok'),
        version: readString(json, 'version'),
      );

  final bool ok;

  final String version;

  Map<String, Object?> toJson() => {
        'ok': ok,
        'version': version,
      };

  List<Issue> validate() => const [];
}

class Invoice {
  Invoice({required this.id, required this.customerId, required this.status, required this.total, required this.lines, this.note, required this.createdAt, required this.updatedAt});

  factory Invoice.fromJson(Map<String, Object?> json) => Invoice(
        id: readInt(json, 'id'),
        customerId: readInt(json, 'customerId'),
        status: Status.fromValue(json['status']),
        total: readString(json, 'total'),
        lines: readList(json, 'lines', (v0) => Line.fromJson(asObject(v0))),
        note: readOptionalString(json, 'note'),
        createdAt: readTimestamp(json, 'createdAt'),
        updatedAt: readTimestamp(json, 'updatedAt'),
      );

  final int id;

  final int customerId;

  final Status status;

  final String total;

  final List<Line> lines;

  final String? note;

  final DateTime createdAt;

  final DateTime updatedAt;

  Map<String, Object?> toJson() => {
        'id': id,
        'customerId': customerId,
        'status': status.value,
        'total': total,
        'lines': [for (final e0 in lines) e0.toJson()],
        if (note != null) 'note': note,
        'createdAt': encodeTimestamp(createdAt),
        'updatedAt': encodeTimestamp(updatedAt),
      };

  List<Issue> validate() => [
        for (final (i0, e0) in lines.indexed) ...[...prefixed(['lines', '$i0'], e0.validate())],
      ];
}

class Line {
  Line({required this.description, required this.quantity, required this.unitPrice});

  factory Line.fromJson(Map<String, Object?> json) => Line(
        description: readString(json, 'description'),
        quantity: readInt(json, 'quantity'),
        unitPrice: readString(json, 'unitPrice'),
      );

  final String description;

  final int quantity;

  final String unitPrice;

  Map<String, Object?> toJson() => {
        'description': description,
        'quantity': quantity,
        'unitPrice': unitPrice,
      };

  List<Issue> validate() => [
        if (description.isEmpty) Issue(['description'], 'required', 'is required'),
        if (description.runes.length > 200) Issue(['description'], 'max', 'must be at most 200 characters'),
        if (quantity < 1) Issue(['quantity'], 'min', 'must be at least 1'),
      ];
}

class ListAttachmentsInput {
  ListAttachmentsInput({required this.invoiceId});

  factory ListAttachmentsInput.fromJson(Map<String, Object?> json) => ListAttachmentsInput(
        invoiceId: readInt(json, 'invoiceId'),
      );

  final int invoiceId;

  Map<String, Object?> toJson() => {
        'invoiceId': invoiceId,
      };

  List<Issue> validate() => [
        if (invoiceId == 0) Issue(['invoiceId'], 'required', 'is required'),
      ];
}

class ListInvoicesInput {
  ListInvoicesInput({this.cursor, required this.limit, this.status});

  factory ListInvoicesInput.fromJson(Map<String, Object?> json) => ListInvoicesInput(
        cursor: readOptionalString(json, 'cursor'),
        limit: readInt(json, 'limit'),
        status: asNullable(json['status'], (v0) => Status.fromValue(v0)),
      );

  final String? cursor;

  final int limit;

  final Status? status;

  Map<String, Object?> toJson() {
    final status = this.status;
    return {
        if (cursor != null) 'cursor': cursor,
        'limit': limit,
        if (status != null) 'status': status.value,
    };
  }

  List<Issue> validate() => [
        if (limit < 1) Issue(['limit'], 'min', 'must be at least 1'),
        if (limit > 100) Issue(['limit'], 'max', 'must be at most 100'),
      ];
}

class Page<T> {
  Page({required this.items, this.nextCursor});

  factory Page.fromJson(Map<String, Object?> json, T Function(Object?) fromJsonT) => Page(
        items: readList(json, 'items', fromJsonT),
        nextCursor: readOptionalString(json, 'nextCursor'),
      );

  final List<T> items;

  final String? nextCursor;

  Map<String, Object?> toJson(Object? Function(T) toJsonT) => {
        'items': [for (final e0 in items) toJsonT(e0)],
        if (nextCursor != null) 'nextCursor': nextCursor,
      };

  List<Issue> validate(List<Issue> Function(T) validateT) => [
        for (final (i0, e0) in items.indexed) ...[...prefixed(['items', '$i0'], validateT(e0))],
      ];
}

class SearchCustomersInput {
  SearchCustomersInput({required this.query});

  factory SearchCustomersInput.fromJson(Map<String, Object?> json) => SearchCustomersInput(
        query: readString(json, 'query'),
      );

  final String query;

  Map<String, Object?> toJson() => {
        'query': query,
      };

  List<Issue> validate() => [
        if (query.isEmpty) Issue(['query'], 'required', 'is required'),
        if (query.runes.length < 2) Issue(['query'], 'min', 'must be at least 2 characters'),
      ];
}

enum Status {
  draft('draft'),
  sent('sent'),
  paid('paid'),
  void_('void');

  const Status(this.value);

  final String value;

  static Status fromValue(Object? value) => values.firstWhere(
        (v) => v.value == value,
        orElse: () => throw FormatException('Status: unknown value $value'),
      );
}

class VoidInvoiceInput {
  VoidInvoiceInput({required this.id});

  factory VoidInvoiceInput.fromJson(Map<String, Object?> json) => VoidInvoiceInput(
        id: readInt(json, 'id'),
      );

  final int id;

  Map<String, Object?> toJson() => {
        'id': id,
      };

  List<Issue> validate() => [
        if (id == 0) Issue(['id'], 'required', 'is required'),
      ];
}

class WatchInput {
  WatchInput({this.status});

  factory WatchInput.fromJson(Map<String, Object?> json) => WatchInput(
        status: asNullable(json['status'], (v0) => Status.fromValue(v0)),
      );

  final Status? status;

  Map<String, Object?> toJson() {
    final status = this.status;
    return {
        if (status != null) 'status': status.value,
    };
  }

  List<Issue> validate() => const [];
}

/// InvoiceLocked is returned when an invoice can no longer change.
class InvoiceLocked {
  InvoiceLocked({required this.id, required this.status});

  factory InvoiceLocked.fromJson(Map<String, Object?> json) => InvoiceLocked(
        id: readInt(json, 'id'),
        status: Status.fromValue(json['status']),
      );

  final int id;

  final Status status;

  Map<String, Object?> toJson() => {
        'id': id,
        'status': status.value,
      };

  List<Issue> validate() => const [];
}

class CustomersClient {
  CustomersClient(this._transport);

  final Transport _transport;

  Future<Customer> get(GetCustomerInput input, {CallOptions? options}) {
    ensureValid(input.validate());
    return _transport.call('customers.get', Method.get, input.toJson(), (json) => Customer.fromJson(asObject(json)), options: options);
  }

  /// Search finds customers whose name or email contains the query.
  Future<Page<Customer>> search(SearchCustomersInput input, {CallOptions? options}) {
    ensureValid(input.validate());
    return _transport.call('customers.search', Method.post, input.toJson(), (json) => Page.fromJson(asObject(json), (v0) => Customer.fromJson(asObject(v0))), options: options);
  }
}

class InvoicesClient {
  InvoicesClient(this._transport);

  final Transport _transport;

  /// Attach stores a file against an invoice.
  Future<Attachment> attach(AttachInput input, Stream<List<int>> file, String filename, {CallOptions? options}) {
    ensureValid(input.validate());
    return _transport.upload('invoices.attach', input.toJson(), file, filename, (json) => Attachment.fromJson(asObject(json)), options: options);
  }

  Future<Page<Attachment>> attachments(ListAttachmentsInput input, {CallOptions? options}) {
    ensureValid(input.validate());
    return _transport.call('invoices.attachments', Method.get, input.toJson(), (json) => Page.fromJson(asObject(json), (v0) => Attachment.fromJson(asObject(v0))), options: options);
  }

  Future<Invoice> create(CreateInvoiceInput input, {CallOptions? options}) {
    ensureValid(input.validate());
    return _transport.call('invoices', Method.post, input.toJson(), (json) => Invoice.fromJson(asObject(json)), options: options);
  }

  /// Get returns one invoice by ID.
  Future<Invoice> get(GetInvoiceInput input, {CallOptions? options}) {
    ensureValid(input.validate());
    return _transport.call('invoices/${Uri.encodeComponent(input.id.toString())}', Method.get, (input.toJson()..remove('id')), (json) => Invoice.fromJson(asObject(json)), options: options, rest: true);
  }

  /// List returns a page of invoices, optionally filtered by status.
  Future<Page<Invoice>> list(ListInvoicesInput input, {CallOptions? options}) {
    ensureValid(input.validate());
    return _transport.call('invoices', Method.get, input.toJson(), (json) => Page.fromJson(asObject(json), (v0) => Invoice.fromJson(asObject(v0))), options: options, rest: true);
  }

  /// Void cancels a draft or sent invoice.
  Future<Invoice> void_(VoidInvoiceInput input, {CallOptions? options}) {
    ensureValid(input.validate());
    return _transport.call('invoices/${Uri.encodeComponent(input.id.toString())}', Method.delete, (input.toJson()..remove('id')), (json) => Invoice.fromJson(asObject(json)), options: options, rest: true);
  }

  /// Watch streams every invoice change.
  Stream<Invoice> watch(WatchInput input, {CallOptions? options}) {
    ensureValid(input.validate());
    return _transport.subscribe('invoices.watch', input.toJson(), (json) => Invoice.fromJson(asObject(json)), options: options);
  }
}

class Client {
  Client(Transport transport)
      : _transport = transport,
        customers = CustomersClient(transport),
        invoices = InvoicesClient(transport);

  final Transport _transport;

  final CustomersClient customers;

  final InvoicesClient invoices;

  Future<HealthOutput> health({CallOptions? options}) {
    return _transport.call('health', Method.get, const {}, (json) => HealthOutput.fromJson(asObject(json)), options: options);
  }
}
