# Code generated by bowline. DO NOT EDIT.

from __future__ import annotations

from collections.abc import AsyncIterator, Iterator
from datetime import datetime
from enum import Enum
from typing import Annotated, BinaryIO, Generic, TypeVar
from urllib.parse import quote

from bowline_client import CallOptions, Empty, Method, SyncTransport, Transport
from pydantic import BaseModel, ConfigDict, Field


T = TypeVar("T")


class AttachInput(BaseModel):
    model_config = ConfigDict(extra="ignore")

    invoiceId: int = Field(gt=0)


class Attachment(BaseModel):
    model_config = ConfigDict(extra="ignore")

    id: int
    invoiceId: int
    name: str
    contentType: str
    size: int
    createdAt: datetime
    updatedAt: datetime


class Customer(BaseModel):
    model_config = ConfigDict(extra="ignore")

    id: int
    name: str = Field(min_length=1)
    email: str = Field(min_length=1, pattern=r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
    createdAt: datetime
    updatedAt: datetime


class GetCustomerInput(BaseModel):
    model_config = ConfigDict(extra="ignore")

    id: int = Field(gt=0)


class GetInvoiceInput(BaseModel):
    model_config = ConfigDict(extra="ignore")

    id: int = Field(gt=0)


class HealthOutput(BaseModel):
    model_config = ConfigDict(extra="ignore")

    ok: bool
    version: str


class Line(BaseModel):
    model_config = ConfigDict(extra="ignore")

    description: str = Field(min_length=1, max_length=200)
    quantity: int = Field(ge=1, le=2147483647)
    unitPrice: str


class CreateInvoiceInput(BaseModel):
    model_config = ConfigDict(extra="ignore")

    customerId: int = Field(gt=0)
    lines: list[Line] = Field(min_length=1)
    note: str | None = Field(default=None, max_length=500)


class ListAttachmentsInput(BaseModel):
    model_config = ConfigDict(extra="ignore")

    invoiceId: int = Field(gt=0)


class Page(BaseModel, Generic[T]):
    model_config = ConfigDict(extra="ignore")

    items: list[T]
    nextCursor: str | None = None


class SearchCustomersInput(BaseModel):
    model_config = ConfigDict(extra="ignore")

    query: str = Field(min_length=2)


class Status(str, Enum):
    StatusDraft = "draft"
    StatusSent = "sent"
    StatusPaid = "paid"
    StatusVoid = "void"


class Invoice(BaseModel):
    model_config = ConfigDict(extra="ignore")

    id: int
    customerId: int
    status: Status
    total: str
    lines: list[Line]
    note: str | None = None
    createdAt: datetime
    updatedAt: datetime


class InvoiceLocked(BaseModel):
    """InvoiceLocked is returned when an invoice can no longer change."""

    model_config = ConfigDict(extra="ignore")

    id: int
    status: Status


class ListInvoicesInput(BaseModel):
    model_config = ConfigDict(extra="ignore")

    cursor: str | None = None
    limit: int = Field(ge=1, le=100)
    status: Status | None = None


class VoidInvoiceInput(BaseModel):
    model_config = ConfigDict(extra="ignore")

    id: int = Field(gt=0)


class WatchInput(BaseModel):
    model_config = ConfigDict(extra="ignore")

    status: Status | None = None


class CustomersClient:
    """Procedures under "customers"."""

    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    async def get(self, input: GetCustomerInput, options: CallOptions | None = None) -> Customer:
        return await self._transport.call("customers.get", Method.GET, input, Customer, options)

    async def search(
        self,
        input: SearchCustomersInput,
        options: CallOptions | None = None,
    ) -> Page[Customer]:
        """Search finds customers whose name or email contains the query."""
        return await self._transport.call(
            "customers.search", Method.POST, input, Page[Customer], options
        )


class InvoicesClient:
    """Procedures under "invoices"."""

    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    async def attach(
        self,
        input: AttachInput,
        file: BinaryIO,
        filename: str,
        options: CallOptions | None = None,
    ) -> Attachment:
        """Attach stores a file against an invoice."""
        return await self._transport.upload(
            "invoices.attach", input, file, filename, Attachment, options
        )

    async def attachments(
        self,
        input: ListAttachmentsInput,
        options: CallOptions | None = None,
    ) -> Page[Attachment]:
        return await self._transport.call(
            "invoices.attachments", Method.GET, input, Page[Attachment], options
        )

    async def create(
        self,
        input: CreateInvoiceInput,
        options: CallOptions | None = None,
    ) -> Invoice:
        return await self._transport.call(
            "invoices", Method.POST, input, Invoice, options, rest=True
        )

    async def get(self, input: GetInvoiceInput, options: CallOptions | None = None) -> Invoice:
        """Get returns one invoice by ID."""
        return await self._transport.call(
            f"invoices/{quote(str(input.id), safe='')}",
            Method.GET,
            input,
            Invoice,
            options,
            rest=True,
            drop=("id",),
        )

    async def list(
        self,
        input: ListInvoicesInput,
        options: CallOptions | None = None,
    ) -> Page[Invoice]:
        """List returns a page of invoices, optionally filtered by status."""
        return await self._transport.call(
            "invoices", Method.GET, input, Page[Invoice], options, rest=True
        )

    async def void(self, input: VoidInvoiceInput, options: CallOptions | None = None) -> Invoice:
        """Void cancels a draft or sent invoice."""
        return await self._transport.call(
            f"invoices/{quote(str(input.id), safe='')}",
            Method.DELETE,
            input,
            Invoice,
            options,
            rest=True,
            drop=("id",),
        )

    def watch(
        self,
        input: WatchInput,
        options: CallOptions | None = None,
    ) -> AsyncIterator[Invoice]:
        """Watch streams every invoice change."""
        return self._transport.subscribe("invoices.watch", input, Invoice, options)


class Client:
    """Transport client for every procedure in the contract."""

    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.customers = CustomersClient(transport)
        self.invoices = InvoicesClient(transport)

    async def health(
        self,
        input: Empty | None = None,
        options: CallOptions | None = None,
    ) -> HealthOutput:
        return await self._transport.call(
            "health", Method.GET, input or Empty(), HealthOutput, options
        )


class SyncCustomersClient:
    """Procedures under "customers"."""

    def __init__(self, transport: SyncTransport) -> None:
        self._transport = transport

    def get(self, input: GetCustomerInput, options: CallOptions | None = None) -> Customer:
        return self._transport.call("customers.get", Method.GET, input, Customer, options)

    def search(
        self,
        input: SearchCustomersInput,
        options: CallOptions | None = None,
    ) -> Page[Customer]:
        """Search finds customers whose name or email contains the query."""
        return self._transport.call("customers.search", Method.POST, input, Page[Customer], options)


class SyncInvoicesClient:
    """Procedures under "invoices"."""

    def __init__(self, transport: SyncTransport) -> None:
        self._transport = transport

    def attach(
        self,
        input: AttachInput,
        file: BinaryIO,
        filename: str,
        options: CallOptions | None = None,
    ) -> Attachment:
        """Attach stores a file against an invoice."""
        return self._transport.upload("invoices.attach", input, file, filename, Attachment, options)

    def attachments(
        self,
        input: ListAttachmentsInput,
        options: CallOptions | None = None,
    ) -> Page[Attachment]:
        return self._transport.call(
            "invoices.attachments", Method.GET, input, Page[Attachment], options
        )

    def create(self, input: CreateInvoiceInput, options: CallOptions | None = None) -> Invoice:
        return self._transport.call("invoices", Method.POST, input, Invoice, options, rest=True)

    def get(self, input: GetInvoiceInput, options: CallOptions | None = None) -> Invoice:
        """Get returns one invoice by ID."""
        return self._transport.call(
            f"invoices/{quote(str(input.id), safe='')}",
            Method.GET,
            input,
            Invoice,
            options,
            rest=True,
            drop=("id",),
        )

    def list(self, input: ListInvoicesInput, options: CallOptions | None = None) -> Page[Invoice]:
        """List returns a page of invoices, optionally filtered by status."""
        return self._transport.call(
            "invoices", Method.GET, input, Page[Invoice], options, rest=True
        )

    def void(self, input: VoidInvoiceInput, options: CallOptions | None = None) -> Invoice:
        """Void cancels a draft or sent invoice."""
        return self._transport.call(
            f"invoices/{quote(str(input.id), safe='')}",
            Method.DELETE,
            input,
            Invoice,
            options,
            rest=True,
            drop=("id",),
        )

    def watch(self, input: WatchInput, options: CallOptions | None = None) -> Iterator[Invoice]:
        """Watch streams every invoice change."""
        return self._transport.subscribe("invoices.watch", input, Invoice, options)


class SyncClient:
    """SyncTransport client for every procedure in the contract."""

    def __init__(self, transport: SyncTransport) -> None:
        self._transport = transport
        self.customers = SyncCustomersClient(transport)
        self.invoices = SyncInvoicesClient(transport)

    def health(
        self,
        input: Empty | None = None,
        options: CallOptions | None = None,
    ) -> HealthOutput:
        return self._transport.call("health", Method.GET, input or Empty(), HealthOutput, options)
