package bench

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"
)

const (
	RawBenchmark     = "BenchmarkRawNetHTTP"
	BowlineBenchmark = "BenchmarkBowline"
	DevLoopBenchmark = "BenchmarkDevLoopUpdate"
	GeneratorPrefix  = "BenchmarkGenerators/"

	OverheadBudget    = 1.05
	DevLoopBudget     = 500 * time.Millisecond
	RegressionPercent = 5.0

	historyLimit = 20
)

type Result struct {
	Name        string  `json:"name"`
	NsPerOp     float64 `json:"nsPerOp"`
	BytesPerOp  int64   `json:"bytesPerOp"`
	AllocsPerOp int64   `json:"allocsPerOp"`
}

type Run struct {
	Commit  string    `json:"commit"`
	RanAt   time.Time `json:"ranAt"`
	GOOS    string    `json:"goos"`
	GOARCH  string    `json:"goarch"`
	Results []Result  `json:"results"`
}

type Regression struct {
	Name     string
	Previous float64
	Current  float64
	Percent  float64
}

func (r Regression) String() string {
	return fmt.Sprintf("%s regressed %.1f%%: %s -> %s", r.Name, r.Percent, formatNs(r.Previous), formatNs(r.Current))
}

func (r Run) Lookup(name string) (Result, bool) {
	for _, result := range r.Results {
		if result.Name == name {
			return result, true
		}
	}
	return Result{}, false
}

func (r Run) Generators() []Result {
	var out []Result
	for _, result := range r.Results {
		if strings.HasPrefix(result.Name, GeneratorPrefix) {
			out = append(out, result)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func Parse(r io.Reader) ([]Result, error) {
	best := map[string]Result{}
	scanner := bufio.NewScanner(r)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) < 4 || !strings.HasPrefix(fields[0], "Benchmark") {
			continue
		}
		result := Result{Name: trimProcs(fields[0])}
		seen := false
		for i := 1; i+1 < len(fields); i++ {
			value, err := strconv.ParseFloat(fields[i], 64)
			if err != nil {
				continue
			}
			switch fields[i+1] {
			case "ns/op":
				result.NsPerOp = value
				seen = true
			case "B/op":
				result.BytesPerOp = int64(value)
			case "allocs/op":
				result.AllocsPerOp = int64(value)
			}
		}
		if !seen {
			continue
		}
		if previous, ok := best[result.Name]; !ok || result.NsPerOp < previous.NsPerOp {
			best[result.Name] = result
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	results := make([]Result, 0, len(best))
	for _, result := range best {
		results = append(results, result)
	}
	sort.Slice(results, func(i, j int) bool { return results[i].Name < results[j].Name })
	return results, nil
}

func trimProcs(name string) string {
	if i := strings.LastIndex(name, "-"); i > 0 {
		if _, err := strconv.Atoi(name[i+1:]); err == nil {
			return name[:i]
		}
	}
	return name
}

func LoadHistory(dir string) ([]Run, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*.json"))
	if err != nil {
		return nil, err
	}
	runs := make([]Run, 0, len(paths))
	for _, path := range paths {
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		var run Run
		if err := json.Unmarshal(data, &run); err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		runs = append(runs, run)
	}
	sort.Slice(runs, func(i, j int) bool { return runs[i].RanAt.Before(runs[j].RanAt) })
	return runs, nil
}

func Regressions(current Run, history []Run) []Regression {
	if len(history) == 0 {
		return nil
	}
	previous := history[len(history)-1]
	var out []Regression
	for _, result := range current.Results {
		before, ok := previous.Lookup(result.Name)
		if !ok || before.NsPerOp <= 0 {
			continue
		}
		percent := (result.NsPerOp/before.NsPerOp - 1) * 100
		if percent > RegressionPercent {
			out = append(out, Regression{Name: result.Name, Previous: before.NsPerOp, Current: result.NsPerOp, Percent: percent})
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Percent > out[j].Percent })
	return out
}

func Render(current Run, history []Run) string {
	var b strings.Builder
	b.WriteString("# Benchmarks\n\n")
	b.WriteString("Regenerated by the `bench-publish` workflow. Every number is the fastest of the repeated runs on a GitHub-hosted runner, so treat the trend as the signal and a single run as noise.\n\n")
	fmt.Fprintf(&b, "Latest run: `%s` on %s/%s at %s.\n\n", shortCommit(current.Commit), current.GOOS, current.GOARCH, current.RanAt.UTC().Format(time.RFC3339))

	b.WriteString("## Handler overhead\n\n")
	raw, hasRaw := current.Lookup(RawBenchmark)
	bowline, hasBowline := current.Lookup(BowlineBenchmark)
	if hasRaw && hasBowline && raw.NsPerOp > 0 {
		ratio := bowline.NsPerOp / raw.NsPerOp
		b.WriteString("| Handler | ns/op | B/op | allocs/op |\n| --- | ---: | ---: | ---: |\n")
		fmt.Fprintf(&b, "| raw `net/http` | %s | %d | %d |\n", formatNs(raw.NsPerOp), raw.BytesPerOp, raw.AllocsPerOp)
		fmt.Fprintf(&b, "| bowline | %s | %d | %d |\n\n", formatNs(bowline.NsPerOp), bowline.BytesPerOp, bowline.AllocsPerOp)
		fmt.Fprintf(&b, "Overhead is %.1f%% against a budget of %.0f%%.\n\n", (ratio-1)*100, (OverheadBudget-1)*100)
	} else {
		b.WriteString("Not measured in this run.\n\n")
	}

	b.WriteString("## Regeneration latency\n\n")
	if devLoop, ok := current.Lookup(DevLoopBenchmark); ok {
		b.WriteString("One edit to a twenty-package synthetic module, reloaded incrementally and reanalyzed.\n\n")
		fmt.Fprintf(&b, "| Measurement | Value | Budget |\n| --- | ---: | ---: |\n| edit to contract | %s | %s |\n\n", formatNs(devLoop.NsPerOp), DevLoopBudget)
	} else {
		b.WriteString("Not measured in this run.\n\n")
	}

	b.WriteString("## Generator throughput\n\n")
	generators := current.Generators()
	if len(generators) > 0 {
		b.WriteString("Contracts rendered per second over the fidelity corpus, one target per row.\n\n")
		b.WriteString("| Target | ns/contract | contracts/s | allocs/contract |\n| --- | ---: | ---: | ---: |\n")
		for _, result := range generators {
			target := strings.TrimPrefix(result.Name, GeneratorPrefix)
			fmt.Fprintf(&b, "| %s | %s | %s | %d |\n", target, formatNs(result.NsPerOp), formatRate(result.NsPerOp), result.AllocsPerOp)
		}
		b.WriteString("\n")
	} else {
		b.WriteString("Not measured in this run.\n\n")
	}

	b.WriteString("## History\n\n")
	runs := append(append([]Run{}, history...), current)
	if len(runs) > historyLimit {
		runs = runs[len(runs)-historyLimit:]
	}
	b.WriteString("| Run | Commit | Overhead | Regeneration | ts generator |\n| --- | --- | ---: | ---: | ---: |\n")
	for _, run := range runs {
		fmt.Fprintf(&b, "| %s | `%s` | %s | %s | %s |\n",
			run.RanAt.UTC().Format("2006-01-02"),
			shortCommit(run.Commit),
			formatRatio(run),
			formatLookup(run, DevLoopBenchmark),
			formatLookup(run, GeneratorPrefix+"ts"))
	}
	b.WriteString("\n")

	regressions := Regressions(current, history)
	b.WriteString("## Regressions\n\n")
	if len(regressions) == 0 {
		fmt.Fprintf(&b, "None over %.0f%% against the previous run.\n", RegressionPercent)
		return b.String()
	}
	fmt.Fprintf(&b, "Over %.0f%% against the previous run:\n\n", RegressionPercent)
	for _, regression := range regressions {
		fmt.Fprintf(&b, "- %s\n", regression)
	}
	return b.String()
}

func formatRatio(run Run) string {
	raw, hasRaw := run.Lookup(RawBenchmark)
	bowline, hasBowline := run.Lookup(BowlineBenchmark)
	if !hasRaw || !hasBowline || raw.NsPerOp <= 0 {
		return "n/a"
	}
	return fmt.Sprintf("%.1f%%", (bowline.NsPerOp/raw.NsPerOp-1)*100)
}

func formatLookup(run Run, name string) string {
	result, ok := run.Lookup(name)
	if !ok {
		return "n/a"
	}
	return formatNs(result.NsPerOp)
}

func formatNs(ns float64) string {
	switch {
	case ns >= 1e9:
		return fmt.Sprintf("%.2f s", ns/1e9)
	case ns >= 1e6:
		return fmt.Sprintf("%.1f ms", ns/1e6)
	case ns >= 1e4:
		return fmt.Sprintf("%.1f µs", ns/1e3)
	}
	return fmt.Sprintf("%.0f ns", ns)
}

func formatRate(ns float64) string {
	if ns <= 0 {
		return "n/a"
	}
	return fmt.Sprintf("%.0f", 1e9/ns)
}

func shortCommit(commit string) string {
	if len(commit) > 12 {
		return commit[:12]
	}
	if commit == "" {
		return "unknown"
	}
	return commit
}
