// Code generated by bowline. DO NOT EDIT.

use bowline_client::{Body, CallOptions, Empty, Error, Issue, Method, Stream, Transport, Validate, encode_segment, rules};
use serde::{Deserialize, Serialize};

/// InvoiceLocked is returned when an invoice can no longer change.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoiceLocked {
    pub id: i64,
    pub status: Status,
}

impl Validate for InvoiceLocked {
    fn validate(&self, _path: &mut Vec<String>, _issues: &mut Vec<Issue>) {}
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachInput {
    #[serde(rename = "invoiceId")]
    pub invoice_id: i64,
}

impl Validate for AttachInput {
    fn validate(&self, path: &mut Vec<String>, issues: &mut Vec<Issue>) {
        rules::required_int(self.invoice_id, path, "invoiceId", issues);
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Attachment {
    pub id: i64,
    #[serde(rename = "invoiceId")]
    pub invoice_id: i64,
    pub name: String,
    #[serde(rename = "contentType")]
    pub content_type: String,
    pub size: i64,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

impl Validate for Attachment {
    fn validate(&self, _path: &mut Vec<String>, _issues: &mut Vec<Issue>) {}
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateInvoiceInput {
    #[serde(rename = "customerId")]
    pub customer_id: i64,
    pub lines: Vec<Line>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

impl Validate for CreateInvoiceInput {
    fn validate(&self, path: &mut Vec<String>, issues: &mut Vec<Issue>) {
        rules::required_int(self.customer_id, path, "customerId", issues);
        rules::required_len(self.lines.len(), path, "lines", issues);
        rules::nested(&self.lines, path, "lines", issues);
        if let Some(v) = &self.note {
            rules::max_len(rules::chars(v), 500, " characters", path, "note", issues);
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Customer {
    pub id: i64,
    pub name: String,
    pub email: String,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

impl Validate for Customer {
    fn validate(&self, path: &mut Vec<String>, issues: &mut Vec<Issue>) {
        rules::required_str(&self.name, path, "name", issues);
        rules::required_str(&self.email, path, "email", issues);
        rules::email(&self.email, path, "email", issues);
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCustomerInput {
    pub id: i64,
}

impl Validate for GetCustomerInput {
    fn validate(&self, path: &mut Vec<String>, issues: &mut Vec<Issue>) {
        rules::required_int(self.id, path, "id", issues);
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetInvoiceInput {
    pub id: i64,
}

impl Validate for GetInvoiceInput {
    fn validate(&self, path: &mut Vec<String>, issues: &mut Vec<Issue>) {
        rules::required_int(self.id, path, "id", issues);
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HealthOutput {
    pub ok: bool,
    pub version: String,
}

impl Validate for HealthOutput {
    fn validate(&self, _path: &mut Vec<String>, _issues: &mut Vec<Issue>) {}
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Invoice {
    pub id: i64,
    #[serde(rename = "customerId")]
    pub customer_id: i64,
    pub status: Status,
    pub total: String,
    pub lines: Vec<Line>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

impl Validate for Invoice {
    fn validate(&self, path: &mut Vec<String>, issues: &mut Vec<Issue>) {
        rules::nested(&self.lines, path, "lines", issues);
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Line {
    pub description: String,
    pub quantity: i32,
    #[serde(rename = "unitPrice")]
    pub unit_price: String,
}

impl Validate for Line {
    fn validate(&self, path: &mut Vec<String>, issues: &mut Vec<Issue>) {
        rules::required_str(&self.description, path, "description", issues);
        rules::max_len(rules::chars(&self.description), 200, " characters", path, "description", issues);
        rules::min_num(self.quantity as f64, 1.0, "1", path, "quantity", issues);
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAttachmentsInput {
    #[serde(rename = "invoiceId")]
    pub invoice_id: i64,
}

impl Validate for ListAttachmentsInput {
    fn validate(&self, path: &mut Vec<String>, issues: &mut Vec<Issue>) {
        rules::required_int(self.invoice_id, path, "invoiceId", issues);
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListInvoicesInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    pub limit: i32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
}

impl Validate for ListInvoicesInput {
    fn validate(&self, path: &mut Vec<String>, issues: &mut Vec<Issue>) {
        rules::min_num(self.limit as f64, 1.0, "1", path, "limit", issues);
        rules::max_num(self.limit as f64, 100.0, "100", path, "limit", issues);
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Page<T> {
    pub items: Vec<T>,
    #[serde(rename = "nextCursor", default, skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
}

impl<T: Validate> Validate for Page<T> {
    fn validate(&self, path: &mut Vec<String>, issues: &mut Vec<Issue>) {
        rules::nested(&self.items, path, "items", issues);
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchCustomersInput {
    pub query: String,
}

impl Validate for SearchCustomersInput {
    fn validate(&self, path: &mut Vec<String>, issues: &mut Vec<Issue>) {
        rules::required_str(&self.query, path, "query", issues);
        rules::min_len(rules::chars(&self.query), 2, " characters", path, "query", issues);
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "sent")]
    Sent,
    #[serde(rename = "paid")]
    Paid,
    #[serde(rename = "void")]
    Void,
}

impl Status {
    pub fn as_str(&self) -> &'static str {
        match self {
            Status::Draft => "draft",
            Status::Sent => "sent",
            Status::Paid => "paid",
            Status::Void => "void",
        }
    }
}

impl Validate for Status {
    fn validate(&self, _path: &mut Vec<String>, _issues: &mut Vec<Issue>) {}
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VoidInvoiceInput {
    pub id: i64,
}

impl Validate for VoidInvoiceInput {
    fn validate(&self, path: &mut Vec<String>, issues: &mut Vec<Issue>) {
        rules::required_int(self.id, path, "id", issues);
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WatchInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
}

impl Validate for WatchInput {
    fn validate(&self, _path: &mut Vec<String>, _issues: &mut Vec<Issue>) {}
}

/// Client calls the API described by the contract.
pub struct Client {
    transport: Transport,
}

impl Client {
    pub fn new(transport: Transport) -> Self {
        Self { transport }
    }

    pub fn transport(&self) -> &Transport {
        &self.transport
    }

    pub fn customers(&self) -> CustomersClient<'_> {
        CustomersClient {
            transport: &self.transport,
        }
    }

    pub fn invoices(&self) -> InvoicesClient<'_> {
        InvoicesClient {
            transport: &self.transport,
        }
    }

    pub async fn health(&self, options: Option<&CallOptions>) -> Result<HealthOutput, Error> {
        self.transport
            .call("health", Method::Get, &Empty {}, options)
            .await
    }
}

/// CustomersClient groups the procedures under "customers".
pub struct CustomersClient<'a> {
    transport: &'a Transport,
}

impl<'a> CustomersClient<'a> {
    pub async fn get(&self, input: &GetCustomerInput, options: Option<&CallOptions>) -> Result<Customer, Error> {
        self.transport
            .call("customers.get", Method::Get, input, options)
            .await
    }

    /// Search finds customers whose name or email contains the query.
    pub async fn search(&self, input: &SearchCustomersInput, options: Option<&CallOptions>) -> Result<Page<Customer>, Error> {
        self.transport
            .call("customers.search", Method::Post, input, options)
            .await
    }
}

/// InvoicesClient groups the procedures under "invoices".
pub struct InvoicesClient<'a> {
    transport: &'a Transport,
}

impl<'a> InvoicesClient<'a> {
    /// Attach stores a file against an invoice.
    pub async fn attach(&self, input: &AttachInput, file: Body, filename: &str, options: Option<&CallOptions>) -> Result<Attachment, Error> {
        self.transport
            .upload("invoices.attach", input, file, filename, options)
            .await
    }

    pub async fn attachments(&self, input: &ListAttachmentsInput, options: Option<&CallOptions>) -> Result<Page<Attachment>, Error> {
        self.transport
            .call("invoices.attachments", Method::Get, input, options)
            .await
    }

    pub async fn create(&self, input: &CreateInvoiceInput, options: Option<&CallOptions>) -> Result<Invoice, Error> {
        self.transport
            .call_rest("invoices", Method::Post, input, &[], options)
            .await
    }

    /// Get returns one invoice by ID.
    pub async fn get(&self, input: &GetInvoiceInput, options: Option<&CallOptions>) -> Result<Invoice, Error> {
        self.transport
            .call_rest(
                &format!("invoices/{}", encode_segment(&input.id)),
                Method::Get,
                input,
                &["id"],
                options,
            )
            .await
    }

    /// List returns a page of invoices, optionally filtered by status.
    pub async fn list(&self, input: &ListInvoicesInput, options: Option<&CallOptions>) -> Result<Page<Invoice>, Error> {
        self.transport
            .call_rest("invoices", Method::Get, input, &[], options)
            .await
    }

    /// Void cancels a draft or sent invoice.
    pub async fn void(&self, input: &VoidInvoiceInput, options: Option<&CallOptions>) -> Result<Invoice, Error> {
        self.transport
            .call_rest(
                &format!("invoices/{}", encode_segment(&input.id)),
                Method::Delete,
                input,
                &["id"],
                options,
            )
            .await
    }

    /// Watch streams every invoice change.
    pub fn watch(&self, input: &WatchInput, options: Option<&CallOptions>) -> impl Stream<Item = Result<Invoice, Error>> + Send + 'static {
        self.transport
            .subscribe("invoices.watch", Method::Get, input, options)
    }
}

