# Code generated by bowline. DO NOT EDIT.

defmodule Ledger.Types.AttachInput do
  @moduledoc false

  alias BowlineClient.Read
  alias BowlineClient.Rules

  @type t :: %__MODULE__{
          invoice_id: integer()
        }

  defstruct [
    :invoice_id
  ]

  @spec from_map(term()) :: t()
  def from_map(json) do
    map = Read.object(json, "AttachInput")

    %__MODULE__{
      invoice_id: Read.int_value(Map.get(map, "invoiceId"), "invoiceId")
    }
  end

  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = v) do
    %{
      "invoiceId" => v.invoice_id
    }
  end

  @spec validate(t()) :: [BowlineClient.Issue.t()]
  def validate(%__MODULE__{} = v) do
    List.flatten([
      Rules.required(["invoiceId"], v.invoice_id)
    ])
  end
end

defmodule Ledger.Types.Attachment do
  @moduledoc false

  alias BowlineClient.Encode
  alias BowlineClient.Read

  @type t :: %__MODULE__{
          id: integer(),
          invoice_id: integer(),
          name: String.t(),
          content_type: String.t(),
          size: integer(),
          created_at: DateTime.t(),
          updated_at: DateTime.t()
        }

  defstruct [
    :id,
    :invoice_id,
    :name,
    :content_type,
    :size,
    :created_at,
    :updated_at
  ]

  @spec from_map(term()) :: t()
  def from_map(json) do
    map = Read.object(json, "Attachment")

    %__MODULE__{
      id: Read.int_value(Map.get(map, "id"), "id"),
      invoice_id: Read.int_value(Map.get(map, "invoiceId"), "invoiceId"),
      name: Read.string_value(Map.get(map, "name"), "name"),
      content_type: Read.string_value(Map.get(map, "contentType"), "contentType"),
      size: Read.int_value(Map.get(map, "size"), "size"),
      created_at: Read.timestamp_value(Map.get(map, "createdAt"), "createdAt"),
      updated_at: Read.timestamp_value(Map.get(map, "updatedAt"), "updatedAt")
    }
  end

  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = v) do
    %{
      "id" => v.id,
      "invoiceId" => v.invoice_id,
      "name" => v.name,
      "contentType" => v.content_type,
      "size" => v.size,
      "createdAt" => Encode.timestamp(v.created_at),
      "updatedAt" => Encode.timestamp(v.updated_at)
    }
  end

  @spec validate(t()) :: [BowlineClient.Issue.t()]
  def validate(%__MODULE__{}), do: []
end

defmodule Ledger.Types.CreateInvoiceInput do
  @moduledoc false

  alias BowlineClient.Encode
  alias BowlineClient.Read
  alias BowlineClient.Rules
  alias Ledger.Types

  @type t :: %__MODULE__{
          customer_id: integer(),
          lines: [Types.Line.t()],
          note: String.t() | nil
        }

  defstruct [
    :customer_id,
    :lines,
    :note
  ]

  @spec from_map(term()) :: t()
  def from_map(json) do
    map = Read.object(json, "CreateInvoiceInput")

    %__MODULE__{
      customer_id: Read.int_value(Map.get(map, "customerId"), "customerId"),
      lines: Read.list_value(Map.get(map, "lines"), "lines", &Types.Line.from_map/1),
      note: Read.optional_value(Map.get(map, "note"), &Read.string_value(&1, "note"))
    }
  end

  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = v) do
    %{
      "customerId" => v.customer_id,
      "lines" => Encode.list(v.lines, &Types.Line.to_map/1)
    }
    |> Encode.optional("note", v.note, &Function.identity/1)
  end

  @spec validate(t()) :: [BowlineClient.Issue.t()]
  def validate(%__MODULE__{} = v) do
    List.flatten([
      Rules.required(["customerId"], v.customer_id),
      Rules.required(["lines"], v.lines),
      Read.validate_list(["lines"], v.lines, &Types.Line.validate/1),
      Rules.max(["note"], v.note, 500)
    ])
  end
end

defmodule Ledger.Types.Customer do
  @moduledoc false

  alias BowlineClient.Encode
  alias BowlineClient.Read
  alias BowlineClient.Rules

  @type t :: %__MODULE__{
          id: integer(),
          name: String.t(),
          email: String.t(),
          created_at: DateTime.t(),
          updated_at: DateTime.t()
        }

  defstruct [
    :id,
    :name,
    :email,
    :created_at,
    :updated_at
  ]

  @spec from_map(term()) :: t()
  def from_map(json) do
    map = Read.object(json, "Customer")

    %__MODULE__{
      id: Read.int_value(Map.get(map, "id"), "id"),
      name: Read.string_value(Map.get(map, "name"), "name"),
      email: Read.string_value(Map.get(map, "email"), "email"),
      created_at: Read.timestamp_value(Map.get(map, "createdAt"), "createdAt"),
      updated_at: Read.timestamp_value(Map.get(map, "updatedAt"), "updatedAt")
    }
  end

  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = v) do
    %{
      "id" => v.id,
      "name" => v.name,
      "email" => v.email,
      "createdAt" => Encode.timestamp(v.created_at),
      "updatedAt" => Encode.timestamp(v.updated_at)
    }
  end

  @spec validate(t()) :: [BowlineClient.Issue.t()]
  def validate(%__MODULE__{} = v) do
    List.flatten([
      Rules.required(["name"], v.name),
      Rules.required(["email"], v.email),
      Rules.email(["email"], v.email)
    ])
  end
end

defmodule Ledger.Types.GetCustomerInput do
  @moduledoc false

  alias BowlineClient.Read
  alias BowlineClient.Rules

  @type t :: %__MODULE__{
          id: integer()
        }

  defstruct [
    :id
  ]

  @spec from_map(term()) :: t()
  def from_map(json) do
    map = Read.object(json, "GetCustomerInput")

    %__MODULE__{
      id: Read.int_value(Map.get(map, "id"), "id")
    }
  end

  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = v) do
    %{
      "id" => v.id
    }
  end

  @spec validate(t()) :: [BowlineClient.Issue.t()]
  def validate(%__MODULE__{} = v) do
    List.flatten([
      Rules.required(["id"], v.id)
    ])
  end
end

defmodule Ledger.Types.GetInvoiceInput do
  @moduledoc false

  alias BowlineClient.Read
  alias BowlineClient.Rules

  @type t :: %__MODULE__{
          id: integer()
        }

  defstruct [
    :id
  ]

  @spec from_map(term()) :: t()
  def from_map(json) do
    map = Read.object(json, "GetInvoiceInput")

    %__MODULE__{
      id: Read.int_value(Map.get(map, "id"), "id")
    }
  end

  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = v) do
    %{
      "id" => v.id
    }
  end

  @spec validate(t()) :: [BowlineClient.Issue.t()]
  def validate(%__MODULE__{} = v) do
    List.flatten([
      Rules.required(["id"], v.id)
    ])
  end
end

defmodule Ledger.Types.HealthOutput do
  @moduledoc false

  alias BowlineClient.Read

  @type t :: %__MODULE__{
          ok: boolean(),
          version: String.t()
        }

  defstruct [
    :ok,
    :version
  ]

  @spec from_map(term()) :: t()
  def from_map(json) do
    map = Read.object(json, "HealthOutput")

    %__MODULE__{
      ok: Read.bool_value(Map.get(map, "ok"), "ok"),
      version: Read.string_value(Map.get(map, "version"), "version")
    }
  end

  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = v) do
    %{
      "ok" => v.ok,
      "version" => v.version
    }
  end

  @spec validate(t()) :: [BowlineClient.Issue.t()]
  def validate(%__MODULE__{}), do: []
end

defmodule Ledger.Types.Invoice do
  @moduledoc false

  alias BowlineClient.Encode
  alias BowlineClient.Read
  alias Ledger.Types

  @type t :: %__MODULE__{
          id: integer(),
          customer_id: integer(),
          status: Types.Status.t(),
          total: String.t(),
          lines: [Types.Line.t()],
          note: String.t() | nil,
          created_at: DateTime.t(),
          updated_at: DateTime.t()
        }

  defstruct [
    :id,
    :customer_id,
    :status,
    :total,
    :lines,
    :note,
    :created_at,
    :updated_at
  ]

  @spec from_map(term()) :: t()
  def from_map(json) do
    map = Read.object(json, "Invoice")

    %__MODULE__{
      id: Read.int_value(Map.get(map, "id"), "id"),
      customer_id: Read.int_value(Map.get(map, "customerId"), "customerId"),
      status: Types.Status.from_value(Map.get(map, "status")),
      total: Read.string_value(Map.get(map, "total"), "total"),
      lines: Read.list_value(Map.get(map, "lines"), "lines", &Types.Line.from_map/1),
      note: Read.optional_value(Map.get(map, "note"), &Read.string_value(&1, "note")),
      created_at: Read.timestamp_value(Map.get(map, "createdAt"), "createdAt"),
      updated_at: Read.timestamp_value(Map.get(map, "updatedAt"), "updatedAt")
    }
  end

  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = v) do
    %{
      "id" => v.id,
      "customerId" => v.customer_id,
      "status" => Types.Status.to_value(v.status),
      "total" => v.total,
      "lines" => Encode.list(v.lines, &Types.Line.to_map/1),
      "createdAt" => Encode.timestamp(v.created_at),
      "updatedAt" => Encode.timestamp(v.updated_at)
    }
    |> Encode.optional("note", v.note, &Function.identity/1)
  end

  @spec validate(t()) :: [BowlineClient.Issue.t()]
  def validate(%__MODULE__{} = v) do
    List.flatten([
      Read.validate_list(["lines"], v.lines, &Types.Line.validate/1)
    ])
  end
end

defmodule Ledger.Types.Line do
  @moduledoc false

  alias BowlineClient.Read
  alias BowlineClient.Rules

  @type t :: %__MODULE__{
          description: String.t(),
          quantity: integer(),
          unit_price: String.t()
        }

  defstruct [
    :description,
    :quantity,
    :unit_price
  ]

  @spec from_map(term()) :: t()
  def from_map(json) do
    map = Read.object(json, "Line")

    %__MODULE__{
      description: Read.string_value(Map.get(map, "description"), "description"),
      quantity: Read.int_value(Map.get(map, "quantity"), "quantity"),
      unit_price: Read.string_value(Map.get(map, "unitPrice"), "unitPrice")
    }
  end

  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = v) do
    %{
      "description" => v.description,
      "quantity" => v.quantity,
      "unitPrice" => v.unit_price
    }
  end

  @spec validate(t()) :: [BowlineClient.Issue.t()]
  def validate(%__MODULE__{} = v) do
    List.flatten([
      Rules.required(["description"], v.description),
      Rules.max(["description"], v.description, 200),
      Rules.min(["quantity"], v.quantity, 1)
    ])
  end
end

defmodule Ledger.Types.ListAttachmentsInput do
  @moduledoc false

  alias BowlineClient.Read
  alias BowlineClient.Rules

  @type t :: %__MODULE__{
          invoice_id: integer()
        }

  defstruct [
    :invoice_id
  ]

  @spec from_map(term()) :: t()
  def from_map(json) do
    map = Read.object(json, "ListAttachmentsInput")

    %__MODULE__{
      invoice_id: Read.int_value(Map.get(map, "invoiceId"), "invoiceId")
    }
  end

  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = v) do
    %{
      "invoiceId" => v.invoice_id
    }
  end

  @spec validate(t()) :: [BowlineClient.Issue.t()]
  def validate(%__MODULE__{} = v) do
    List.flatten([
      Rules.required(["invoiceId"], v.invoice_id)
    ])
  end
end

defmodule Ledger.Types.ListInvoicesInput do
  @moduledoc false

  alias BowlineClient.Encode
  alias BowlineClient.Read
  alias BowlineClient.Rules
  alias Ledger.Types

  @type t :: %__MODULE__{
          cursor: String.t() | nil,
          limit: integer(),
          status: Types.Status.t() | nil
        }

  defstruct [
    :cursor,
    :limit,
    :status
  ]

  @spec from_map(term()) :: t()
  def from_map(json) do
    map = Read.object(json, "ListInvoicesInput")

    %__MODULE__{
      cursor: Read.optional_value(Map.get(map, "cursor"), &Read.string_value(&1, "cursor")),
      limit: Read.int_value(Map.get(map, "limit"), "limit"),
      status: Read.optional_value(Map.get(map, "status"), &Types.Status.from_value/1)
    }
  end

  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = v) do
    %{
      "limit" => v.limit
    }
    |> Encode.optional("cursor", v.cursor, &Function.identity/1)
    |> Encode.optional("status", v.status, &Types.Status.to_value/1)
  end

  @spec validate(t()) :: [BowlineClient.Issue.t()]
  def validate(%__MODULE__{} = v) do
    List.flatten([
      Rules.min(["limit"], v.limit, 1),
      Rules.max(["limit"], v.limit, 100)
    ])
  end
end

defmodule Ledger.Types.Page do
  @moduledoc false

  alias BowlineClient.Encode
  alias BowlineClient.Read

  @type t(param_t) :: %__MODULE__{
          items: [param_t],
          next_cursor: String.t() | nil
        }

  defstruct [
    :items,
    :next_cursor
  ]

  @spec from_map(term(), (term() -> term())) :: t(term())
  def from_map(json, decode_t) do
    map = Read.object(json, "Page")

    %__MODULE__{
      items: Read.list_value(Map.get(map, "items"), "items", decode_t),
      next_cursor: field_next_cursor(map)
    }
  end

  @spec to_map(t(term()), (term() -> term())) :: map()
  def to_map(%__MODULE__{} = v, encode_t) do
    %{
      "items" => Encode.list(v.items, encode_t)
    }
    |> Encode.optional("nextCursor", v.next_cursor, &Function.identity/1)
  end

  @spec validate(t(term()), (term() -> [BowlineClient.Issue.t()])) :: [BowlineClient.Issue.t()]
  def validate(%__MODULE__{} = v, validate_t) do
    List.flatten([
      Read.validate_list(["items"], v.items, validate_t)
    ])
  end

  defp field_next_cursor(map) do
    Read.optional_value(Map.get(map, "nextCursor"), &Read.string_value(&1, "nextCursor"))
  end
end

defmodule Ledger.Types.SearchCustomersInput do
  @moduledoc false

  alias BowlineClient.Read
  alias BowlineClient.Rules

  @type t :: %__MODULE__{
          query: String.t()
        }

  defstruct [
    :query
  ]

  @spec from_map(term()) :: t()
  def from_map(json) do
    map = Read.object(json, "SearchCustomersInput")

    %__MODULE__{
      query: Read.string_value(Map.get(map, "query"), "query")
    }
  end

  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = v) do
    %{
      "query" => v.query
    }
  end

  @spec validate(t()) :: [BowlineClient.Issue.t()]
  def validate(%__MODULE__{} = v) do
    List.flatten([
      Rules.required(["query"], v.query),
      Rules.min(["query"], v.query, 2)
    ])
  end
end

defmodule Ledger.Types.Status do
  @moduledoc false

  alias BowlineClient.Read

  @type t :: :draft | :sent | :paid | :void

  @spec from_value(term()) :: t()
  def from_value("draft"), do: :draft
  def from_value("sent"), do: :sent
  def from_value("paid"), do: :paid
  def from_value("void"), do: :void

  def from_value(other) do
    Read.mismatch("Status", "one of draft, sent, paid, void", other)
  end

  @spec to_value(t()) :: String.t()
  def to_value(:draft), do: "draft"
  def to_value(:sent), do: "sent"
  def to_value(:paid), do: "paid"
  def to_value(:void), do: "void"
end

defmodule Ledger.Types.VoidInvoiceInput do
  @moduledoc false

  alias BowlineClient.Read
  alias BowlineClient.Rules

  @type t :: %__MODULE__{
          id: integer()
        }

  defstruct [
    :id
  ]

  @spec from_map(term()) :: t()
  def from_map(json) do
    map = Read.object(json, "VoidInvoiceInput")

    %__MODULE__{
      id: Read.int_value(Map.get(map, "id"), "id")
    }
  end

  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = v) do
    %{
      "id" => v.id
    }
  end

  @spec validate(t()) :: [BowlineClient.Issue.t()]
  def validate(%__MODULE__{} = v) do
    List.flatten([
      Rules.required(["id"], v.id)
    ])
  end
end

defmodule Ledger.Types.WatchInput do
  @moduledoc false

  alias BowlineClient.Encode
  alias BowlineClient.Read
  alias Ledger.Types

  @type t :: %__MODULE__{
          status: Types.Status.t() | nil
        }

  defstruct [
    :status
  ]

  @spec from_map(term()) :: t()
  def from_map(json) do
    map = Read.object(json, "WatchInput")

    %__MODULE__{
      status: Read.optional_value(Map.get(map, "status"), &Types.Status.from_value/1)
    }
  end

  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = v) do
    %{}
    |> Encode.optional("status", v.status, &Types.Status.to_value/1)
  end

  @spec validate(t()) :: [BowlineClient.Issue.t()]
  def validate(%__MODULE__{}), do: []
end

defmodule Ledger.Types.InvoiceLocked do
  @moduledoc """
  InvoiceLocked is returned when an invoice can no longer change.
  """

  alias BowlineClient.Read
  alias Ledger.Types

  @type t :: %__MODULE__{
          id: integer(),
          status: Types.Status.t()
        }

  defstruct [
    :id,
    :status
  ]

  @spec from_map(term()) :: t()
  def from_map(json) do
    map = Read.object(json, "InvoiceLocked")

    %__MODULE__{
      id: Read.int_value(Map.get(map, "id"), "id"),
      status: Types.Status.from_value(Map.get(map, "status"))
    }
  end

  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = v) do
    %{
      "id" => v.id,
      "status" => Types.Status.to_value(v.status)
    }
  end

  @spec validate(t()) :: [BowlineClient.Issue.t()]
  def validate(%__MODULE__{}), do: []
end

defmodule Ledger.Customers do
  @moduledoc "Procedures under customers."

  alias BowlineClient.Transport
  alias Ledger.Types

  @doc """
  get calls customers.get.
  """
  @spec get(Transport.t(), Types.GetCustomerInput.t(), Transport.call_opts()) ::
          {:ok, Types.Customer.t()} | {:error, BowlineClient.Error.t()}
  def get(transport, %Types.GetCustomerInput{} = input, opts \\ []) do
    Transport.call(
      transport,
      "customers.get",
      :get,
      Types.GetCustomerInput.to_map(input),
      &Types.Customer.from_map/1,
      opts
    )
  end

  @spec get!(Transport.t(), Types.GetCustomerInput.t(), Transport.call_opts()) ::
          Types.Customer.t()
  def get!(transport, input, opts \\ []) do
    case get(transport, input, opts) do
      {:ok, value} -> value
      {:error, error} -> raise error
    end
  end

  @doc """
  Search finds customers whose name or email contains the query.
  """
  @spec search(Transport.t(), Types.SearchCustomersInput.t(), Transport.call_opts()) ::
          {:ok, Types.Page.t(Types.Customer.t())} | {:error, BowlineClient.Error.t()}
  def search(transport, %Types.SearchCustomersInput{} = input, opts \\ []) do
    Transport.call(
      transport,
      "customers.search",
      :post,
      Types.SearchCustomersInput.to_map(input),
      &decode_output/1,
      opts
    )
  end

  @spec search!(Transport.t(), Types.SearchCustomersInput.t(), Transport.call_opts()) ::
          Types.Page.t(Types.Customer.t())
  def search!(transport, input, opts \\ []) do
    case search(transport, input, opts) do
      {:ok, value} -> value
      {:error, error} -> raise error
    end
  end

  defp decode_output(value) do
    Types.Page.from_map(value, &Types.Customer.from_map/1)
  end
end

defmodule Ledger.Invoices do
  @moduledoc "Procedures under invoices."

  alias BowlineClient.Transport
  alias Ledger.Types

  @doc """
  Attach stores a file against an invoice.
  """
  @spec attach(
          Transport.t(),
          Types.AttachInput.t(),
          Enumerable.t() | binary(),
          String.t(),
          Transport.call_opts()
        ) ::
          {:ok, Types.Attachment.t()} | {:error, BowlineClient.Error.t()}
  def attach(transport, %Types.AttachInput{} = input, file, filename, opts \\ []) do
    Transport.upload(
      transport,
      "invoices.attach",
      Types.AttachInput.to_map(input),
      file,
      filename,
      &Types.Attachment.from_map/1,
      opts
    )
  end

  @doc """
  attachments calls invoices.attachments.
  """
  @spec attachments(Transport.t(), Types.ListAttachmentsInput.t(), Transport.call_opts()) ::
          {:ok, Types.Page.t(Types.Attachment.t())} | {:error, BowlineClient.Error.t()}
  def attachments(transport, %Types.ListAttachmentsInput{} = input, opts \\ []) do
    Transport.call(
      transport,
      "invoices.attachments",
      :get,
      Types.ListAttachmentsInput.to_map(input),
      &decode_output/1,
      opts
    )
  end

  @spec attachments!(Transport.t(), Types.ListAttachmentsInput.t(), Transport.call_opts()) ::
          Types.Page.t(Types.Attachment.t())
  def attachments!(transport, input, opts \\ []) do
    case attachments(transport, input, opts) do
      {:ok, value} -> value
      {:error, error} -> raise error
    end
  end

  @doc """
  create calls invoices.create.
  """
  @spec create(Transport.t(), Types.CreateInvoiceInput.t(), Transport.call_opts()) ::
          {:ok, Types.Invoice.t()} | {:error, BowlineClient.Error.t()}
  def create(transport, %Types.CreateInvoiceInput{} = input, opts \\ []) do
    Transport.call(
      transport,
      "invoices.create",
      :post,
      Types.CreateInvoiceInput.to_map(input),
      &Types.Invoice.from_map/1,
      opts
    )
  end

  @spec create!(Transport.t(), Types.CreateInvoiceInput.t(), Transport.call_opts()) ::
          Types.Invoice.t()
  def create!(transport, input, opts \\ []) do
    case create(transport, input, opts) do
      {:ok, value} -> value
      {:error, error} -> raise error
    end
  end

  @doc """
  Get returns one invoice by ID.
  """
  @spec get(Transport.t(), Types.GetInvoiceInput.t(), Transport.call_opts()) ::
          {:ok, Types.Invoice.t()} | {:error, BowlineClient.Error.t()}
  def get(transport, %Types.GetInvoiceInput{} = input, opts \\ []) do
    Transport.call(
      transport,
      "invoices.get",
      :get,
      Types.GetInvoiceInput.to_map(input),
      &Types.Invoice.from_map/1,
      opts
    )
  end

  @spec get!(Transport.t(), Types.GetInvoiceInput.t(), Transport.call_opts()) :: Types.Invoice.t()
  def get!(transport, input, opts \\ []) do
    case get(transport, input, opts) do
      {:ok, value} -> value
      {:error, error} -> raise error
    end
  end

  @doc """
  List returns a page of invoices, optionally filtered by status.
  """
  @spec list(Transport.t(), Types.ListInvoicesInput.t(), Transport.call_opts()) ::
          {:ok, Types.Page.t(Types.Invoice.t())} | {:error, BowlineClient.Error.t()}
  def list(transport, %Types.ListInvoicesInput{} = input, opts \\ []) do
    Transport.call(
      transport,
      "invoices.list",
      :get,
      Types.ListInvoicesInput.to_map(input),
      &decode_output_2/1,
      opts
    )
  end

  @spec list!(Transport.t(), Types.ListInvoicesInput.t(), Transport.call_opts()) ::
          Types.Page.t(Types.Invoice.t())
  def list!(transport, input, opts \\ []) do
    case list(transport, input, opts) do
      {:ok, value} -> value
      {:error, error} -> raise error
    end
  end

  @doc """
  Void cancels a draft or sent invoice.
  """
  @spec void(Transport.t(), Types.VoidInvoiceInput.t(), Transport.call_opts()) ::
          {:ok, Types.Invoice.t()} | {:error, BowlineClient.Error.t()}
  def void(transport, %Types.VoidInvoiceInput{} = input, opts \\ []) do
    Transport.call(
      transport,
      "invoices.void",
      :post,
      Types.VoidInvoiceInput.to_map(input),
      &Types.Invoice.from_map/1,
      opts
    )
  end

  @spec void!(Transport.t(), Types.VoidInvoiceInput.t(), Transport.call_opts()) ::
          Types.Invoice.t()
  def void!(transport, input, opts \\ []) do
    case void(transport, input, opts) do
      {:ok, value} -> value
      {:error, error} -> raise error
    end
  end

  @doc """
  Watch streams every invoice change.
  """
  @spec watch(Transport.t(), Types.WatchInput.t(), Transport.call_opts()) ::
          {:ok, Enumerable.t()} | {:error, BowlineClient.Error.t()}
  def watch(transport, %Types.WatchInput{} = input, opts \\ []) do
    Transport.subscribe(
      transport,
      "invoices.watch",
      Types.WatchInput.to_map(input),
      &Types.Invoice.from_map/1,
      opts
    )
  end

  defp decode_output(value) do
    Types.Page.from_map(value, &Types.Attachment.from_map/1)
  end

  defp decode_output_2(value) do
    Types.Page.from_map(value, &Types.Invoice.from_map/1)
  end
end

defmodule Ledger.Client do
  @moduledoc """
  Entry point for the API: `new/2` builds the transport every module takes first.

  Mounted modules:
  - `Ledger.Customers`
  - `Ledger.Invoices`
  """

  alias BowlineClient.Transport
  alias Ledger.Types

  @spec new(String.t(), keyword()) :: Transport.t()
  def new(base_url, opts \\ []) do
    Transport.new(Keyword.put(opts, :base_url, base_url))
  end

  @doc """
  health calls health.
  """
  @spec health(Transport.t(), Transport.call_opts()) ::
          {:ok, Types.HealthOutput.t()} | {:error, BowlineClient.Error.t()}
  def health(transport, opts \\ []) do
    Transport.call(transport, "health", :get, %{}, &Types.HealthOutput.from_map/1, opts)
  end

  @spec health!(Transport.t(), Transport.call_opts()) :: Types.HealthOutput.t()
  def health!(transport, opts \\ []) do
    case health(transport, opts) do
      {:ok, value} -> value
      {:error, error} -> raise error
    end
  end

  @doc "Decodes the details of a declared error variant into its struct; nil for other errors."
  @spec error_details(BowlineClient.Error.t()) :: struct() | nil
  def error_details(%BowlineClient.Error{type: "InvoiceLocked", details: details})
      when is_map(details) do
    Types.InvoiceLocked.from_map(details)
  end

  def error_details(%BowlineClient.Error{}), do: nil
end
